server:
  port: 8080

spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
management:
  server:
    port: 8091
  endpoints:
    web:
      exposure:
        include: prometheus,health
  metrics:
    enable:
      all: true
  endpoint:
    prometheus:
      enabled: true
